# -*- coding: utf-8 -*-
"""guess .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-YTZF7licl1P_GvRvaIFydP5jhaoHSZu
"""

import random

number = random.randint(1, 100)
guess = 0

while guess != number:
  guess = int(input("enter guess:"))

  if (guess < number):
    print("Guess higher!")
  elif(guess > number):
    print("Guess lower!")
  else:
    print("you won!")