# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-YTZF7licl1P_GvRvaIFydP5jhaoHSZu
"""

unit=input("Is this temperature is celsius or fahrenheit(C/F):")
temp=float(input("enter the temperature:"))

if unit == "C":
  temp = round((9*temp)/ 5 +32,1)
  print(f"The temperature in fahrenhit is:{temp}°F")
elif unit== "F":
  temp = round((temp-32)*5/9,1) # Fixed: Indentation corrected here
  print(f"The temperature in celsius is:{temp}°C") # Fixed: Indentation corrected here
else:
  print(f"{unit} is an invalid unit of measurement")